### ISSUE TITLE
Datapack verison 1.18. on server

### ISSUE THREAD

**Issue by Tomik151cz** [ICY105/Mechanization#150]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).

Datapack-Utilities-3.4.1, MechConfig_v3.1.0, Mechanization_v3.1.0 and on server is resourcepack MechResourcepack_v3.1.0.zip
2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
Datapack is running on PaperMC 1.18
4. What if happening vs. what you expect to happen?
When I use /function give:mech_all everything is ok, but I can craft nothing, and mechanical manual dont work too.

![image](https://user-images.githubusercontent.com/72154020/144702728-6fc5e7c8-d1f5-4659-b2d7-fb2c7e00b6ea.png)

![image](https://user-images.githubusercontent.com/72154020/144702750-9b2475c5-2ce4-4966-9411-0259010c71c7.png)
![image](https://user-images.githubusercontent.com/72154020/144702770-851ac0e2-d208-4251-9ad2-e41ddb43506a.png)

where is problem

**Comment by CrunchylnMilk** [comment]
That "Triggered (mech manual) set value to *x*" message is normal. Due to the limits of Minecraft, clicking the icon for the section you want doesn't actually take you there. Instead, it's best to think of it as the icons set the content for the rest of the book. 

After you click the icon for the section you want, click the forward arrow in the right lower corner to actually go there and start reading.

As for the machine table, that's weird, it looks like your layout is right. Try breaking the table with the wrench (shift + right click with the wrench) and replacing it.

I suppose it's possible it's some sort of weird interaction with paper as well, but last I heard, things were generally working well on that front.
